### ISSUE TITLE
Misprint in Client.zep

### ISSUE THREAD

**Issue by jagdtiger9** [crocodile2u/zhandlersocket#2]
Hello, Victor!
There's possibly a misprint in your Client.zep file.
Method createConnection() always use portWrite prop.
`protected function createConnection(int port) {`
`    return new Connection(this->host, this->portWrite, this->getUsePersistentConnection(), this->logger);`
`}`

**Comment by crocodile2u** [comment]
Nice catch. Checkout this commit: https://github.com/crocodile2u/zhandlersocket/commit/262bc686ac9db1a3d0dcba86376816b45d7babe5

A minor release (v1.0.1) has been also published
