### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by MoneyCoder** [crocodile2u/zhandlersocket#3]
Warning: Invalid callback Zhandlersocket\Index::__construct, cannot access protected method Zhandlersocket\Index::__construct() in /var/www/public/test1.php on line 11

Fatal error: Uncaught RuntimeException: Call to undefined method ::__construct() in /var/www/public/test1.php:11 Stack trace: #0 /var/www/public/test1.php(11): Zhandlersocket\Client->getIndex('mydb', 'test', 'PRIMARY', Array, Array) #1 {main} thrown in /var/www/public/test1.php on line 11

**Comment by MoneyCoder** [comment]
Compiled on PHP 7.1, and my code:

error_reporting(E_ALL);
ini_set('display_errors', 'on');
use \Zhandlersocket\Client;

$client = new Client();
$index = $client->getIndex("mydb", "test", "PRIMARY", ["id", "genre", "title", "view_count"], ["genre"]);

my table

`CREATE TABLE test ( id int not null auto_increment PRIMARY KEY, genre VARCHAR(20) NOT NULL, title varchar(100) NOT NULL, view_count INT NOT NULL DEFAULT 0, KEY(genre) ) ENGINE InnoDB`

**Comment by crocodile2u** [comment]
On my Ubuntu 17.10 with PHP 7.0 I can't see the problem. Will try to reproduce on 7.1.

**Comment by crocodile2u** [comment]
Fixed in v1.2.0
