### ISSUE TITLE
error with zephir>0.9.6

### ISSUE THREAD

**Issue by laurenti** [crocodile2u/zhandlersocket#4]
If i compile with zephir version > 0.9.6 I get error : 

> php: symbol lookup error: zhandlersocket.so: undefined symbol: zephir_set_called_scope

**Comment by sergeyklay** [comment]
Use latest stable Zephir

**Comment by crocodile2u** [comment]
For me, it worked just fine  right now with Zephir 0.9.9. Also its worth to notice that it may be required to run zephir fullclean, especially if you updated your PHP version since you last built the extension.

**Comment by laurenti** [comment]
Indeed, I update PHP from 7.0 to 7.1 , I installed zephir again and run fullclean, but I get this error.
There were 2 errors in compile-errors.log file, but now I do not have the file, Only if I install again version 0.9.9. I think it's related to the change " Removed zephir_set_called_scope() " https://github.com/phalcon/zephir/commit/37d5b126f5fc0b93d3e6cf6d057740f86c8a471f#diff-85c94f6879135b062771356b12abd283

Another zep's works smoothly.

**Comment by crocodile2u** [comment]
Thanks for the feedback. I still don't have PHP 7.1 yet

**Comment by crocodile2u** [comment]
Compiled with PHP 7.1 without errors. Got a runtime error then when running unit tests though.

**Comment by crocodile2u** [comment]
As for the runtime error, see https://github.com/crocodile2u/zhandlersocket/issues/3, I'm about to fix it and draft a new release

**Comment by crocodile2u** [comment]
Fixed in v1.2.0
